### ISSUE TITLE
Add a new hook to find missing table group label 

### ISSUE THREAD

**Issue by yu-iskw** [Cold-Bore-Capital/lightdash-pre-commit#2]
We can define table groups with `models[].meta.group_label`. It would be very useful to find missing table group labels for us.

```yaml
version: 2

models:
  - name: my_table
    meta:
      label: 'My Custom Table Name'
      order_fields_by: 'label'
      group_label: 'Revenue'
      sql_filter: ${date_dimension} > '2020-01-01'
      joins:
        - join: my_other_table
          sql_on: ${my_table.column_a} = ${my_other_table.column_a}
      required_attributes:
        is_admin: 'true'
```

https://docs.lightdash.com/references/tables/#group-label
